

language: node_js
node_js: 0.8.6

services: 
  - mongodb

notifications:
  email:
    recipients:
      - mark.nijhof@avira.com
	  - peter.kuenst@avira.com
	  - andreas.arnegger@avira.com
	  - markus.hinderhofer@avira.com
	  - markus.leutner@avira.com
	  - johannes.schuster@avira.com
	  - oana.stoica@avira.com
	  - adrian.vlad@avira.com
	  - gerhard.herbert@avira.com
	  - benjamin.beermann@avira.com
	  - sebastian.faller@avira.com
	  
    on_success: change 
    on_failure: always 

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

script:
  - "./deployment/deploy.sh run-me"

